[package]
name = "dbgphmm"
version = "0.1.0"
authors = ["Ryo Nakabayashi <ryonakabayashi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_bench"
harness = false

[dependencies]
bio = "*"
rand = "0.8"
approx = "*"
arrayvec = "*"
fnv = "1.0.3"
