name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
# upload rust doc
#  doc:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - uses: actions/checkout@v3
#    - name: Run doc
#      run: cargo doc --no-deps
#    - name: Deploy
#      uses: actions/upload-pages-artifact@v1
#      with:
#        path: target/doc
